### ISSUE TITLE
search-guard-kibana-plugin 5.2.2 over https not reachable 

### ISSUE THREAD

**Issue by Passpes** [floragunncom/search-guard-kibana-plugin#11]
I'm using search-guard-kibana-plugin 5.2.2 and its working over HTTP (/)
Before the use of search-guard-kibana-plugin I had HTTPS enabled and working for Kibana, but now when I integrate search-guard-kibana-plugin with HTTPS the host is not reachable at all..

```
server.port: 5563
server.host: mykibana

# Setup SSL
server.ssl.cert: "/etc/kibana/mykibana.crt"
server.ssl.key: "/etc/kibana/mykibana.key"

# Enables you to specify a path to mount Kibana at if you are running behind a proxy. This setting
# cannot end in a slash.
# server.basePath: ""

# The maximum payload size in bytes for incoming server requests.
# server.maxPayloadBytes: 1048576

kibana.index: ".kibana-ingdiba"

logging.dest: /var/log/kibana/mykibana

elasticsearch.ssl.ca: "/etc/kibana/root-ca.pem"
elasticsearch.ssl.verify: false
elasticsearch.username: "kibanaserver"
elasticsearch.password: "kibanaserver"
elasticsearch.url: "https://mykibana:9200"

console.proxyConfig:
  - match:
      protocol: "https"
    ssl:
      ca: "/etc/kibana/root-ca.pem"

searchguard.cookie.password: "365dwdfdwwe3e55f6fe5wfdq65wefedw"
searchguard.cookie.secure: true
searchguard.basicauth.enabled: false
```

Logs from kibana:
`{"type":"log","@timestamp":"2017-03-13T13:50:45Z","tags":["connection","client","error"],"pid":17960,"level":"error","message":"Parse Error","error":{"message":"Parse Error","name":"Error","stack":"Error: Parse Error\n    at Error (native)","code":"HPE_INVALID_METHOD"}}`
