### ISSUE TITLE
Default index will be unset sometimes in tenants

### ISSUE THREAD

**Issue by Foxeronie** [floragunncom/search-guard-kibana-plugin#195]
Hi everyone,

since our update from 6.2.4 to 6.6.1 we have the problem that sometimes the default index is not set anymore in some tenants.
It only seems to happen, if multiple people use the tenant.
So personA uses Tenant 'Example'. Then if personB is accessing the tenant and data it happens that personA will be redirected to the index management site, because no default index is set.
I already tried to reinstall Kibana and the module. I also deleted the .kibana tenant index, but the problem still exists.

All machines running Ubuntu 16.04.

Package: elasticsearch
Version: 6.6.1
elasticsearch::plugin "com.floragunn:search-guard-6:6.6.1-24.1"

Package: kibana
Version: 6.6.1
kibana plugin: search-guard-kibana-plugin-6.6.1-18.3.zip

kibana.yml
```
searchguard:
    cookie:
        password: "<some_string>"
        secure: true
    multitenancy:
        enabled: true
        tenants:
            preferred:
                - private
                - global
    basicauth:
        login:
            brandimage: <some_string>
```

elasticsearch.yml
```
searchguard.audit.config.disabled_rest_categories: NONE
searchguard.audit.config.disabled_transport_categories: NONE
searchguard.audit.config.type: doc
searchguard.audit.ignore_users:
- logstash
- kibanaserver
searchguard.audit.type: internal_elasticsearch
searchguard.authcz.admin_dn:
- <some_string>
searchguard.enterprise_modules_enabled: true
searchguard.restapi.roles_enabled:
- sg_admin
searchguard.ssl.http.enabled: true
searchguard.ssl.http.pemcert_filepath: <some_string>
searchguard.ssl.http.pemkey_filepath: <some_string>
searchguard.ssl.http.pemtrustedcas_filepath: <some_string>
searchguard.ssl.transport.enable_openssl_if_available: false
searchguard.ssl.transport.enabled: true
searchguard.ssl.transport.enforce_hostname_verification: true
searchguard.ssl.transport.keystore_alias: <some_string>
searchguard.ssl.transport.keystore_filepath: <some_string>
searchguard.ssl.transport.keystore_password: "${R_STRING}"
searchguard.ssl.transport.keystore_type: JKS
searchguard.ssl.transport.resolve_hostname: true
searchguard.ssl.transport.truststore_alias: root-ca-chain
searchguard.ssl.transport.truststore_filepath: ssl/truststore.jks
searchguard.ssl.transport.truststore_password: "${R_STRING}"
searchguard.ssl.transport.truststore_type: JKS
xpack.security.enabled: 'false'
```

sg_config.yml:
```
searchguard:
  dynamic:
    license: <some_string>
    multi_rolespan_enabled: true
    kibana:
      do_not_fail_on_forbidden: true
      multitenancy_enabled: true
      server_username: 'kibanaserver'
      index: '.kibana'
    http:
      anonymous_auth_enabled: false
      xff:
        enabled: false
    authc:
      basic_internal_auth_domain:
        http_enabled: true
        transport_enabled: true
        order: 1
        http_authenticator:
          type: basic
          challenge: true
        authentication_backend:
          type: intern
      ldap:
        enabled: true
        http_enabled: true
        transport_enabled: false
        order: 0
        http_authenticator:
          type: basic
          challenge: true
        authentication_backend:
          type: ldap
          config:
            enable_ssl: true
            enable_start_tls: false
            enable_ssl_client_auth: false
            verify_hostnames: false
            hosts:
              - <some_string>
            bind_dn: <some_string>
            password: <some_string>
            userbase: <some_string>
            usersearch: <some_string>
            username_attribute: uid
```

Please tell me, if you need additional informations.

Best regards,
Patrick

**Comment by floragunncom** [comment]
@jochenkressin @mgustafsson1 can you have a look?

**Comment by jochenkressin** [comment]
I guess we will need to try to reproduce this. At first glance, the configuration seems fine to me.

Is this behavior reproducible consistently? Means can I use the following steps to reproduce?

"So personA uses Tenant 'Example'. Then if personB is accessing the tenant and data it happens that personA will be redirected to the index management site, because no default index is set." 

Also, if I understood correctly, you did not experience this issue with 6.2.4, correct?

**Comment by pdanysz** [comment]
Dears,

ELK 6.6.2
Kibana 6.6.2
SG 18.3

He have similar issue, and this must be some kind of Bug :( We don't know yeat if this is Kibana 6.6.2 or SG 18.3 issue.

But here are what we found after deeper debug:

1. When you setup "default" index in Management Index Patterns,  Kibana GUI is sending below request to the Kibana server:
```
POST /api/kibana/settings HTTP/1.1
...
...
Payload:
{changes: {defaultIndex: "AWbyPlChK-J4cs1B0hK2"}}
changes: {defaultIndex: "AWbyPlChK-J4cs1B0hK2"}
defaultIndex: "AWbyPlChK-J4cs1B0hK2"
```

And after when Kibana send above request to Save information about Default Pattern, we check the tenant **"multikibana...-tenant-"index** for looking for "**defaultIndex**" field and yea, we found it with the value as above Payload is.

Next we click the "Discovery" tab for "searching" we find out that Kibana is sending again above request, but with "empty" payload, as fallows:
```
{changes: {defaultIndex: null}}
changes: {defaultIndex: null}
defaultIndex: null
```
And as result is that Kibana redirecting back  to "Index Patterns" again.

This is happening even when you create new index patterns from scratch and tries to setup some Defaults. Result after few clicks on Kibana are the same - no default patter sets and Kibana is sending about request with "null" in defaultIndex.

This is kind of urgent because our tenants are complain on it 👎 :( 

**How to recreate this issue:**
1. Login to kibana
2. Select Tenant
3. Go to Index Management -> Index Pattern
4. Setup some pattern and Select "default"
5. Click Discovery Tab 
6. If is working on Discovery Tab, then click CANVAS and when Canvas loads , click back to Discovery then Kibana in 99% should redirect again to Index Patterns setup.

Thats all what we found.
I hope this help with debugging.

**Comment by khavert** [comment]
Hi, it looks like trouble with cookies. From time to time when I pick up tenant X and go to management-> index patterns  I see all indices from Global. 

For now as a workaround we added extra index_pattern for each of tenants:

`PUT <tenant_indice>/doc/index-pattern:bugpattern
{"index-pattern" : {
              "notExpandable" : true,
              "timeFieldName" : "@timestamp",
              "title" : "select_index",
              "fields" : """[{"name":"@timestamp","type":"date","count":0,"scripted":false,"searchable":true,"aggregatable":true,"readFromDocValues":true},{"name":"@version","type":"string","count":0,"scripted":false,"searchable":true,"aggregatable":false,"readFromDocValues":false}]"""
            },
            "type" : "index-pattern"
          }`

And modify:
src/legacy/core_plugins/kibana/public/discover/controllers/discover.js
src/ui/public/index_patterns/route_setup/load_default.js

with rule IF defaultindex === null then set it to bugpattern.

it's not pretty solution but works as we have major incident with it. 

so now the case with posting null defaultIndex looks like:
`changes: {defaultIndex: "bugpattern"}`

**Comment by jochenkressin** [comment]
@khavert which version of SG and the KI plugin are you using? It seems this issue only surfaces for specific ES/KI versions.

**Comment by pdanysz** [comment]
Me @khavert are from the same company :) 
We are using Kibana 6.6.2 + SG 18.3 version :)

**Comment by Foxeronie** [comment]
> Is this behavior reproducible consistently? Means can I use the following steps to reproduce?
We tried some szenarios, but mostly it seems to be random. An example:

Both in Inkognito:
A: Login
B: Login
A: Select TenantA
B: Select TenantA
A: Show Index Pattern (default is set)
B: Show Index Pattern (default is set)
A: Page refresh via F5 (still set)
B: Page refresh via F5 (still set)
A: Discover (still set)
B: Discover (still set)
A: Page refresh via F5 (default is NOT set anymore)
B: Page refresh via F5 (still set)
A: Page refresh via F5 (default is set again)
B: Page refresh via F5 (still set)
A: From Index Patterns Site pressing Discover (default is set again)
B: Going to Canvas and back (still set)
B: Page refresh via F5 (default is NOT set anymore)
A: Discover (still set)
B: Page refresh via F5 (default is set again)

> Also, if I understood correctly, you did not experience this issue with 6.2.4, correct?
That's correct. The problem started for us after the upgrade to 6.6.1

**Comment by jochenkressin** [comment]
ok, did not know that ;) Also, adding @mgustafsson1 to this thread

**Comment by jochenkressin** [comment]
@Foxeronie @pdanysz @khavert this is really strange. We were not able to reproduce this in the last days, testing on different lab environments here. We also tried to forcefully delete cookies, emptying the session storage etc. Still no luck. So we are basically looking for any differences in your setup and ours.

@pdanysz You write that in your case "Kibana in 99% should redirect again to Index Patterns setup." so the behavior seems to be very consistent with your setup. Can you share your kibana.yml?

Also: 

* does anyone run multiple instances of Kibana against the same ES cluster?
* do you use RO tenants?
* is the GLOBAL tenant enabled or disabled?
* what browsers are you using? Anything exotic here?

Thanks for your input, this seems like a Heisenbug. We will continue to investigate.

**Comment by pdanysz** [comment]
@jochenkressin 
Yes this is very consistent, but sometimes it looks like @Foxeronie shows :D 

Tomorrow when I will be at the office and I will put some config for u.

Anyway, 
- we have kibana run on Openshift (docker/kubernetes)
- normalny we are running with one instance of kibana so it shouldn't be a problem with multiple instances accessing the same index + caching
- AFAK we don't have RO tenants (confirm also tomorrow), but Global is enabled
- mainly we use Chrome, but other our colleagues are using IE or FF but I don't have confirmed issue on those browser (tomorrow I will ask them to test)

In last week we migrated from 5.6 to 6.6.2 and problems starts after upgrade. Unfortunately undetected by us on the beginning.

**Comment by jochenkressin** [comment]
Another question: Elastic has introduced the Spaces with 6.5. Is anyone of you using that alongside the SG multi-tenancy feature? If you are not actively using it, can you try to disable it and see if it makes a difference?

`xpack.spaces.enabled: false`

**Comment by Foxeronie** [comment]
> * does anyone run multiple instances of Kibana against the same ES cluster?
> * do you use RO tenants?
> * is the GLOBAL tenant enabled or disabled?
> * what browsers are you using? Anything exotic here?
> 
> Thanks for your input, this seems like a Heisenbug. We will continue to investigate.

- We have two Kibana server runnig and in front of them is a F5 Loadbalancer. One of the servers is only a fall-back and not used by clients until the first one goes down. (We will test, if this still happens when we access the server directly, tomorrow)

- our defined roles:
```
sg_admin:
  readonly: true
  cluster:
    - UNLIMITED
  indices:
    '*':
      '*':
        - UNLIMITED
  tenants:
    Administration: RW

sg_admin_ro:
  readonly: true
  cluster:
    - CLUSTER_MONITOR
    - CLUSTER_COMPOSITE_OPS
  indices:
    '*':
      '*':
        - READ
  tenants:
    Administration: RW

sg_logstash:
  cluster:
    - CLUSTER_MONITOR
    - CLUSTER_COMPOSITE_OPS
    - indices:admin/template/get
    - indices:admin/template/put
  indices:
    '*':
      '*':
        - CRUD
        - CREATE_INDEX

sg_kibana_user:
  readonly: true
  cluster:
    - INDICES_MONITOR
    - CLUSTER_COMPOSITE_OPS
    - indices:data/read/scroll/clear
    - cluster:admin/ingest/pipeline/simulate
  indices:
    '?kibana':
      '*':
        - MANAGE
        - INDEX
        - READ
        - DELETE
    '?kibana-6':
      '*':
        - MANAGE
        - INDEX
        - READ
        - DELETE
    '?kibana_*':
      '*':
        - MANAGE
        - INDEX
        - READ
        - DELETE
    '?tasks':
      '*':
        - INDICES_ALL
    '?management-beats':
      '*':
        - INDICES_ALL
    '*':
      '*':
        - indices:data/read/field_caps*
        - indices:data/read/xpack/rollup*
        - indices:admin/mappings/get*
        - indices:admin/get

sg_kibana_server:
  readonly: true
  cluster:
      - CLUSTER_MONITOR
      - CLUSTER_COMPOSITE_OPS
      - cluster:admin/xpack/monitoring*
      - indices:admin/template*
      - indices:data/read/scroll*
  indices:
    '*':
      '*':
        - INDICES_ALL

### X-Pack COMPATIBILITY
sg_xp_monitoring:
  readonly: true
  cluster:
    - cluster:monitor/xpack/info
    - cluster:monitor/main
    - cluster:admin/xpack/monitoring/bulk
  indices:
    '?monitor*':
      '*':
        - INDICES_ALL

sg_xp_alerting:
  readonly: true
  cluster:
    - indices:data/read/scroll
    - cluster:admin/xpack/watcher*
    - cluster:monitor/xpack/watcher*
  indices:
    '?watches*':
      '*':
        - INDICES_ALL
    '?watcher-history-*':
      '*':
        - INDICES_ALL
    '?triggered_watches':
      '*':
        - INDICES_ALL
    '*':
      '*':
        - READ
        - indices:admin/aliases/get

sg_xp_machine_learning:
  readonly: true
  cluster:
    - cluster:admin/persistent*
    - cluster:internal/xpack/ml*
    - indices:data/read/scroll*
    - cluster:admin/xpack/ml*
    - cluster:monitor/xpack/ml*
  indices:
    '*':
      '*':
        - READ
        - indices:admin/get*
    '?ml-*':
      '*':
        - "*"

sg_manage_snapshots:
  cluster:
    - MANAGE_SNAPSHOTS
  indices:
    '*':
      '*':
        - "indices:data/write/index"
        - "indices:admin/create"

sg_own_index:
  indices:
    '${user_name}':
      '*':
        - INDICES_ALL
```
- The different tenant roles we have created always look like this.
```
role_tenantA:
  indices:
    'tenantA-*':
      '*':
        - READ
        - SEARCH
  tenants:
    tenantA: RW
```

- The global tenant ist active.
- We are not using any exotic browsers. Mostly FF and Chrome/Chromium.

Other specific configurations in our instance
- elastic is not installed on kibana servers
- complete kibana config:
```
server:
    port: 8443
    host: "<ip_addr>"
    name: "host.domain.de"
    ssl:
        enabled: true
        certificate: <some_string>
        key: <some_string>
kibana:
    index: ".kibana"
elasticsearch:
    hosts:
      - https://ip_1:9200
      - https://ip_2:9200
      - https://ip_3:9200
      - https://ip_4:9200
      - https://ip_5:9200
      - https://ip_6:9200
    username: "kibanaserver"
    password: "<some_string>"
    requestTimeout: 180000
    requestHeadersWhitelist: ["sgtenant", "Authorization"]
    ssl:
        certificateAuthorities: [ "<some_string>" ]
        verificationMode: none
console:
    enabled: false
timelion:
    enabled: false
logging:
    dest: /var/log/kibana/kibana.log
    silent: false
    quiet: false
    verbose: false
searchguard:
    cookie:
        password: "<some_string>"
        secure: true
    multitenancy:
        enabled: true
        tenants:
            preferred:
                - private
                - global
    basicauth:
        login:
            brandimage: <some_string>

xpack:
    security:
        enabled: false
    graph:
        enabled: false
    ml:
        enabled: false
    monitoring:
        enabled: false
    reporting:
        enabled: true
    watcher:
        enabled: false
    infra:
        enabled: false
    apm:
        enabled: false
    spaces:
        enabled: false
    canvas:
        enabled: true

sentinl:
    es:
        hosts:
            - host: '<ip_addr>'
              port: 9200
              protocol: 'https'
            - host: '<ip_addr>'
              port: 9200
              protocol: 'https'
            - host: '<ip_addr>'
              port: 9200
              protocol: 'https'
            - host: '<ip_addr>'
              port: 9200
              protocol: 'https'
            - host: '<ip_addr>'
              port: 9200
              protocol: 'https'
            - host: '<ip_addr>'
              port: 9200
              protocol: 'https'
    settings:
        email:
            active: true
            user: '<some_string>'
            password: '<some_string>'
            host: 'host.domain.de'
            port: 587
            domain: 'domain.de'
            ssl: false
            tls: true
```

> Login to kibana
> Select Tenant
> Go to Index Management -> Index Pattern
> Setup some pattern and Select "default"
> Click Discovery Tab
> If is working on Discovery Tab, then click CANVAS and when Canvas loads , click back to Discovery then Kibana in 99% should redirect again to Index Patterns setup.

I can't reproduce the problem this way. It's working fine multiple times.

- xpack.spaces is already disabled
- It's not happening, if I use a tenant alone

There are two index templates for kibana defined (not by us)

kibana_index_template:.kibana
```
{
  "order": 0,
  "index_patterns": [
    ".kibana"
  ],
  "settings": {
    "index": {
      "number_of_shards": "1",
      "auto_expand_replicas": "0-1"
    }
  },
  "mappings": {
    "doc": {
      "dynamic": "strict",
      "properties": {
        "config": {
          "dynamic": "true",
          "properties": {
            "buildNum": {
              "type": "keyword"
            }
          }
        },
        "migrationVersion": {
          "dynamic": "true",
          "type": "object"
        },
        "type": {
          "type": "keyword"
        },
        "namespace": {
          "type": "keyword"
        },
        "updated_at": {
          "type": "date"
        },
        "telemetry": {
          "properties": {
            "enabled": {
              "type": "boolean"
            }
          }
        },
        "canvas-workpad": {
          "dynamic": false,
          "properties": {
            "name": {
              "type": "text",
              "fields": {
                "keyword": {
                  "type": "keyword"
                }
              }
            },
            "id": {
              "type": "text",
              "index": false
            },
            "@timestamp": {
              "type": "date"
            },
            "@created": {
              "type": "date"
            }
          }
        },
        "sentinl-watcher": {
          "properties": {
            "wizard": {
              "type": "object",
              "enabled": false
            },
            "input": {
              "type": "object",
              "enabled": false
            },
            "actions": {
              "type": "object",
              "enabled": false
            },
            "transform": {
              "type": "object",
              "enabled": false
            },
            "condition": {
              "type": "object",
              "enabled": false
            },
            "trigger": {
              "type": "object",
              "enabled": false
            },
            "report": {
              "type": "boolean"
            },
            "disable": {
              "type": "boolean"
            },
            "save_payload": {
              "type": "boolean"
            },
            "impersonate": {
              "type": "boolean"
            },
            "spy": {
              "type": "boolean"
            },
            "title": {
              "type": "text"
            },
            "username": {
              "type": "text"
            },
            "sentinl": {
              "type": "object",
              "enabled": false
            },
            "dashboard_link": {
              "type": "text"
            },
            "custom": {
              "type": "object",
              "enabled": false
            }
          }
        },
        "sentinl-user": {
          "properties": {
            "username": {
              "type": "text"
            },
            "sha": {
              "type": "text"
            },
            "password": {
              "type": "text"
            }
          }
        },
        "index-pattern": {
          "properties": {
            "fieldFormatMap": {
              "type": "text"
            },
            "fields": {
              "type": "text"
            },
            "intervalName": {
              "type": "keyword"
            },
            "notExpandable": {
              "type": "boolean"
            },
            "sourceFilters": {
              "type": "text"
            },
            "timeFieldName": {
              "type": "keyword"
            },
            "title": {
              "type": "text"
            },
            "type": {
              "type": "keyword"
            },
            "typeMeta": {
              "type": "keyword"
            }
          }
        },
        "visualization": {
          "properties": {
            "description": {
              "type": "text"
            },
            "kibanaSavedObjectMeta": {
              "properties": {
                "searchSourceJSON": {
                  "type": "text"
                }
              }
            },
            "savedSearchId": {
              "type": "keyword"
            },
            "title": {
              "type": "text"
            },
            "uiStateJSON": {
              "type": "text"
            },
            "version": {
              "type": "integer"
            },
            "visState": {
              "type": "text"
            }
          }
        },
        "search": {
          "properties": {
            "columns": {
              "type": "keyword"
            },
            "description": {
              "type": "text"
            },
            "hits": {
              "type": "integer"
            },
            "kibanaSavedObjectMeta": {
              "properties": {
                "searchSourceJSON": {
                  "type": "text"
                }
              }
            },
            "sort": {
              "type": "keyword"
            },
            "title": {
              "type": "text"
            },
            "version": {
              "type": "integer"
            }
          }
        },
        "dashboard": {
          "properties": {
            "description": {
              "type": "text"
            },
            "hits": {
              "type": "integer"
            },
            "kibanaSavedObjectMeta": {
              "properties": {
                "searchSourceJSON": {
                  "type": "text"
                }
              }
            },
            "optionsJSON": {
              "type": "text"
            },
            "panelsJSON": {
              "type": "text"
            },
            "refreshInterval": {
              "properties": {
                "display": {
                  "type": "keyword"
                },
                "pause": {
                  "type": "boolean"
                },
                "section": {
                  "type": "integer"
                },
                "value": {
                  "type": "integer"
                }
              }
            },
            "timeFrom": {
              "type": "keyword"
            },
            "timeRestore": {
              "type": "boolean"
            },
            "timeTo": {
              "type": "keyword"
            },
            "title": {
              "type": "text"
            },
            "uiStateJSON": {
              "type": "text"
            },
            "version": {
              "type": "integer"
            }
          }
        },
        "url": {
          "properties": {
            "accessCount": {
              "type": "long"
            },
            "accessDate": {
              "type": "date"
            },
            "createDate": {
              "type": "date"
            },
            "url": {
              "type": "text",
              "fields": {
                "keyword": {
                  "type": "keyword",
                  "ignore_above": 2048
                }
              }
            }
          }
        },
        "server": {
          "properties": {
            "uuid": {
              "type": "keyword"
            }
          }
        },
        "kql-telemetry": {
          "properties": {
            "optInCount": {
              "type": "long"
            },
            "optOutCount": {
              "type": "long"
            }
          }
        }
      }
    }
  },
  "aliases": {}
}
```

kibana_index_template:.kibana_*
```
{
  "order": 0,
  "index_patterns": [
    ".kibana_*"
  ],
  "settings": {
    "index": {
      "number_of_shards": "1"
    }
  },
  "mappings": {
    "doc": {
      "dynamic": "strict",
      "properties": {
        "config": {
          "dynamic": "true",
          "properties": {
            "buildNum": {
              "type": "keyword"
            }
          }
        },
        "migrationVersion": {
          "dynamic": "true",
          "type": "object"
        },
        "type": {
          "type": "keyword"
        },
        "namespace": {
          "type": "keyword"
        },
        "updated_at": {
          "type": "date"
        },
        "telemetry": {
          "properties": {
            "enabled": {
              "type": "boolean"
            }
          }
        },
        "canvas-workpad": {
          "dynamic": false,
          "properties": {
            "name": {
              "type": "text",
              "fields": {
                "keyword": {
                  "type": "keyword"
                }
              }
            },
            "id": {
              "type": "text",
              "index": false
            },
            "@timestamp": {
              "type": "date"
            },
            "@created": {
              "type": "date"
            }
          }
        },
        "sentinl-watcher": {
          "properties": {
            "wizard": {
              "type": "object",
              "enabled": false
            },
            "input": {
              "type": "object",
              "enabled": false
            },
            "actions": {
              "type": "object",
              "enabled": false
            },
            "transform": {
              "type": "object",
              "enabled": false
            },
            "condition": {
              "type": "object",
              "enabled": false
            },
            "trigger": {
              "type": "object",
              "enabled": false
            },
            "report": {
              "type": "boolean"
            },
            "disable": {
              "type": "boolean"
            },
            "save_payload": {
              "type": "boolean"
            },
            "impersonate": {
              "type": "boolean"
            },
            "spy": {
              "type": "boolean"
            },
            "title": {
              "type": "text"
            },
            "username": {
              "type": "text"
            },
            "sentinl": {
              "type": "object",
              "enabled": false
            },
            "dashboard_link": {
              "type": "text"
            },
            "custom": {
              "type": "object",
              "enabled": false
            }
          }
        },
        "sentinl-user": {
          "properties": {
            "username": {
              "type": "text"
            },
            "sha": {
              "type": "text"
            },
            "password": {
              "type": "text"
            }
          }
        },
        "index-pattern": {
          "properties": {
            "fieldFormatMap": {
              "type": "text"
            },
            "fields": {
              "type": "text"
            },
            "intervalName": {
              "type": "keyword"
            },
            "notExpandable": {
              "type": "boolean"
            },
            "sourceFilters": {
              "type": "text"
            },
            "timeFieldName": {
              "type": "keyword"
            },
            "title": {
              "type": "text"
            },
            "type": {
              "type": "keyword"
            },
            "typeMeta": {
              "type": "keyword"
            }
          }
        },
        "visualization": {
          "properties": {
            "description": {
              "type": "text"
            },
            "kibanaSavedObjectMeta": {
              "properties": {
                "searchSourceJSON": {
                  "type": "text"
                }
              }
            },
            "savedSearchId": {
              "type": "keyword"
            },
            "title": {
              "type": "text"
            },
            "uiStateJSON": {
              "type": "text"
            },
            "version": {
              "type": "integer"
            },
            "visState": {
              "type": "text"
            }
          }
        },
        "search": {
          "properties": {
            "columns": {
              "type": "keyword"
            },
            "description": {
              "type": "text"
            },
            "hits": {
              "type": "integer"
            },
            "kibanaSavedObjectMeta": {
              "properties": {
                "searchSourceJSON": {
                  "type": "text"
                }
              }
            },
            "sort": {
              "type": "keyword"
            },
            "title": {
              "type": "text"
            },
            "version": {
              "type": "integer"
            }
          }
        },
        "dashboard": {
          "properties": {
            "description": {
              "type": "text"
            },
            "hits": {
              "type": "integer"
            },
            "kibanaSavedObjectMeta": {
              "properties": {
                "searchSourceJSON": {
                  "type": "text"
                }
              }
            },
            "optionsJSON": {
              "type": "text"
            },
            "panelsJSON": {
              "type": "text"
            },
            "refreshInterval": {
              "properties": {
                "display": {
                  "type": "keyword"
                },
                "pause": {
                  "type": "boolean"
                },
                "section": {
                  "type": "integer"
                },
                "value": {
                  "type": "integer"
                }
              }
            },
            "timeFrom": {
              "type": "keyword"
            },
            "timeRestore": {
              "type": "boolean"
            },
            "timeTo": {
              "type": "keyword"
            },
            "title": {
              "type": "text"
            },
            "uiStateJSON": {
              "type": "text"
            },
            "version": {
              "type": "integer"
            }
          }
        },
        "url": {
          "properties": {
            "accessCount": {
              "type": "long"
            },
            "accessDate": {
              "type": "date"
            },
            "createDate": {
              "type": "date"
            },
            "url": {
              "type": "text",
              "fields": {
                "keyword": {
                  "type": "keyword",
                  "ignore_above": 2048
                }
              }
            }
          }
        },
        "server": {
          "properties": {
            "uuid": {
              "type": "keyword"
            }
          }
        },
        "kql-telemetry": {
          "properties": {
            "optInCount": {
              "type": "long"
            },
            "optOutCount": {
              "type": "long"
            }
          }
        }
      }
    }
  },
  "aliases": {}
}
```
