### ISSUE TITLE
Kerberos authentication - Elasticsearch & Kibana

### ISSUE THREAD

**Issue by xetter9** [floragunncom/search-guard-kibana-plugin#278]
I have installed SearchGuard into Elasticsearch and Kibana then set to use Kerberos. When I start kibana, it says **Authentication Exception**

Here are the configuration I did:

Elasticsearch.yml
cluster.name: aaa
node.name: aa
network.host: 192.168.1.x
http.port: 9201
transport.tcp.port: 9301
cluster.initial_master_nodes: aa
I am using the demo certificates so the searchguard.ssl.transport.pemcert_filepath inside elasticsearch.yml will be default.

I have also added the below in the elasticsearch.yml

```
searchguard.kerberos.acceptor_keytab_filepath: <filename>.keytab
searchguard.kerberos.acceptor_principal: 'HTTP\localhost'
searchguard.kerberos.krb5_filepath: krb5.conf
```
In the sg_config.yml file: I have changed the following

```
authc:
   kerberos_auth_domain:
     http_enabled: true
     transport_enabled: true
     order: 1
     http_authenticator:
       type: kerberos
       challenge: true
       config:
              krb_debug: true
              strip_realm_from_principal: true
    basic_internal_auth_domain:
       http_enabled: true
       transport_enabled: true
       order: 0
       http_authenticator:
          type: basic
          challenge: false
```
everything remains the same for the sg_config.yml

Kibana.yml
```
server.port: 5602
server.host: "0.0.0.0"
elasticsearch.hosts: ["https://192.168.1.x:9201"]
elasticsearch.preserveHost: true
kibana.index: ".kibana"
elasticsearch.requestHeadersWhitelist: ["Negotiate Authorization"]
searchguard.auth.type: "kerberos"
```

I am using Elasticsearch and Kibana version 7.1
